version: '3'

services:
# UI experiment
  ui:
    build: ubuntu-ui/.
    environment:
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
    volumes:
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY

# User permission experiment
  as-user:
    image: alpine:latest
    userns_mode: "host"
    # second ${USER_ID} is for the group. Using the "user private group"
    # https://security.ias.edu/how-and-why-user-private-groups-unix
    user: ${USER_ID}:${USER_ID} 
    working_dir: /tmp
    volumes: 
      - ${PWD}:/tmp

# Network tests
## No network
  no-net:
    image: alpine:latest
    network_mode: "none"

## Default network
  defnet:
    image: adiazmor/docker-ubuntu-with-ping
    # Docker default https://docs.docker.com/network/#network-drivers
    # This leads to all containers from this project to share the same bridge
    # network_mode: "bridge" 
  
  